title: MY TIPITAKA translate
description: bla bla bla
theme: just-the-docs

url: https://yukach.github.io/tipitaka-yk

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
